### PR TITLE
ISSUE-30 pass full path into islandora_datastream_crud_dsfilename_to_pid

### PR DESCRIPTION
**Pull request by wgilling**
second attempt with a valid comment that ends with a period

### CODE REVIEW

**Comment by mjordan** [comment]
Awesome, thanks, I'll test.

**Comment by mjordan** [comment]
@bgilling I've tested pushing datastream files for objects that have autoincremented PIDs (i.e., not containing periods) and it doesn't appear to cause any side effects. In other words, it doesn't break anything. I haven't tested it with PIDs that contain periods since it isn't trivial to load objects that have such PIDs (unless you have a trick to share on how to do that). But based on the lack of side effects, I am willing to merge this PR into 7.x if you are satisfied that it works with PIDs containing periods.

**Comment by mjordan** [comment]
@bgilling sorry, I'd like to look at this a bit more closely. Hang tight....

**Comment by wgilling** [comment]
Mark, 

That is a good point... we are likely going to switch back to using the auto-generated PID values, but a lot of our content was ingested with an old script that directly set the PID values.  I am not sure if there 

The example below is taken from some of our scripts that creates finding aids objects.  It may be easier to use the Islandora constructObject function in a devel/php window.

`// Load the Tuque Library with some of our own functions added.
require_once(dirname(__FILE__) .'/../uls-tuque-lib.php');

// Setup Tuque
$path_to_tuque = get_config_value('tuque','path_to_tuque');
if (file_exists($path_to_tuque)) {
        require_once($path_to_tuque . 'Cache.php');
        require_once($path_to_tuque . 'FedoraApi.php');
        require_once($path_to_tuque . 'FedoraApiSerializer.php');
        require_once($path_to_tuque . 'Object.php');
        require_once($path_to_tuque . 'Repository.php');
        require_once($path_to_tuque . 'RepositoryConnection.php');
} else {
        print "Error - Invalid path to Tuque.\n";
        exit(1);
}

$connection = getRepositoryConnection();
$repository = getRepository($connection);

$assigned_pid = 'islandora:2003.x02.01';
$object = $repository->constructObject($assigned_pid);
// Setting the object's models value should create a RELS-EXT and a nearly empty DC.
$object->models = 'islandora:sp_large_image_cmodel';
$repository->ingestObject($object);
`

At this point in time, there should be an object with the PID value of "islandora:2003.x02.01" and it would have a RELS-EXT and DC datastream.

**Comment by mjordan** [comment]
OK, I'll test creating a new object with this script later today. Thanks!

I also left a comment on #30 about a new bug I found (not related to this PR). Let me test with this script before I merge.

**Pull request merged**
