### PR TITLE
add option update object title

### PR DESCRIPTION
**Pull request by giancarlobi**
Mark, 
I added option to ingesting datastream (--update_objectlabel) that if enable the object title is updated with DC title field when DS is DC. I checked and I think is ok, please verify.
Giancarlo

### CODE REVIEW

**Comment by mjordan** [comment]
@giancarlobi cool, I'll take a look.

**Comment by mjordan** [comment]
@giancarlobi I've tested this and it works as intended. Thanks! I've also made some changes to get the code to pass code style checks, and to add logic so that the object's label is only changed if it differs from the new label; I've also added the old title to the log entry. Here's the code:

``` php
    // Update object label from DC if specified.
    if ((drush_get_option('update_object_label')) AND ($dsid == 'DC')) {
      $dublincore = file_get_contents($ds_path);
      $dc_xml = new SimpleXmlElement($dublincore);
      $namespaces = $dc_xml->getNameSpaces(TRUE);
      $dc = $dc_xml->children($namespaces['dc']);
      $new_title = $dc->title;
      if ($new_title != $object->label) {
        $old_title = $object->label;
        $object->label = $new_title;
        islandora_datastream_crud_write_crudlog($pid, $dsid, 'Object label updated from "' . $old_title . '" to "' . $new_title . '"');
      }
    }
```

I hope these chances are OK. If they are, I'll merge from my modified local branch and close this PR, of course giving you full credit for the improvment. Let me know if this is OK.

**Comment by mjordan** [comment]
Also, I've documented in the README how this new option works and the implications of using it (since we're modifying the object, using this option will fire all of the 'hook_islandora_object_modified()' and related hook implementations).

**Comment by giancarlobi** [comment]
Mark,

it's perfect!

.. and credits are for you, you wrote more code than me!!

ciao

Giancarlo

**Pull request merged**
