### PR TITLE
Delete datastream versions

### PR DESCRIPTION
**Pull request by bondjimbond**
Covers #53

This is a replacement pull for #77 in case Pat isn't able to finish up the changes requested there.

# Interested parties

@mjordan

### CODE REVIEW

**Comment by mjordan** [comment]
@patdunlavey OK to move to this new PR and close your original one?

**Comment by patdunlavey** [comment]
Apologies, guys. I've been offline the past couple days. Yes, please feel free to take over this issue. And thanks for finding the `--versions=0` bug!

Shall I close my original PR now?

**Comment by mjordan** [comment]
Yes please, close it. I'm sorry I dropped the ball on this so long ago.

**Comment by bondjimbond** [comment]
@mjordan Do you need to do any more testing on this, given I've added commits?

**Comment by mjordan** [comment]
No, if your changes are ready to go, I can merge. One more thing - since this is a delete operation, and not reversible, can you review the docs for it in the README to make sure they are clear and that a suitably grave warning is there?

**Comment by bondjimbond** [comment]
@mjordan I think the `delete_datastreams` warning is sufficiently dire, but I added some documentation about the specific ways you can enter the `--versions` option.

**Comment by mjordan** [comment]
Very good. I'll find some time to test this evening and if all is well, will merge.

**Comment by mjordan** [comment]
Tested, and works as intended. I have two suggestions, and I can do them after we merge if you want:

1. provide an example of the command at the end of the new section you added to the readme, e.g. `drush islandora_datastream_crud_delete_datastreams --user=admin --dsid=MODS --versions=1.. --pid_file=/tmp/ds_versions_delete.pids`
1. write an entry to the watchdog on successful deletion/failed deletion of a datastream version.

**Comment by bondjimbond** [comment]
I added the example command. Let's leave the watchdog entry for after merge.

**Comment by mjordan** [comment]
@patdunlavey thanks for getting this started and @bondjimbond thanks for bringing it home. I'll merge.

**Comment by patdunlavey** [comment]
Thanks to you both!!

**Pull request merged**
